### ISSUE TITLE
Fallback does not work if obtain the user avatar based on the input from email.

### ISSUE THREAD

**Issue by nnbelous** [Kikobeats/unavatar#64]
Fallback does not work if obtain the user avatar based on the input from email. 
For example:
https://unavatar.now.sh/jgjhsdgfjsd?fallback=https://i.imgur.com/0d1TFfQ.jpg - works
https://unavatar.now.sh/jgjhs@dgfjsd?fallback=https://i.imgur.com/0d1TFfQ.jpg - not working, shows default avatar. Reason in @.

**Comment by Kikobeats** [comment]
That's because gravatar is returning a fallback avatar by default

https://github.com/Kikobeats/unavatar/blob/8fc7ed07263baed6e9dcf8340511e1bed4c9525c/src/providers/index.js#L16

Two possible solutions there:

- maybe we can disable this behavior?
- be possible to detect default gravatar and avoid using it.

**Comment by nnbelous** [comment]
I get it, thanks for the answer.
