### ISSUE TITLE
Instagram not working

### ISSUE THREAD

**Issue by ahmadnassri** [Kikobeats/unavatar#98]
possibly being blocked on now.sh instance

**Comment by ahmadnassri** [comment]
FYI, I recently learned about adding `/?__a=1` to instagram URLs returns the `_sharedData` object as JSON ... that might help, and potentially bypass the block ... though I have not tested this myself in a hosted environment (local IPs are not blocked)

**Comment by ZTF666** [comment]
> /?__a=1

yeah i tried that too and it works , it gives access to the "profile_pic_url_hd" which can be returned and displayed as the result to fix the issue

**Comment by aslafy-z** [comment]
This should be re-opened @Kikobeats, sorry for that.

**Comment by Kikobeats** [comment]
Essentially this is failing based on the same Twitter issue, see #121

**Comment by Gummibeer** [comment]
Instagram has blocked all profile pages for unauthenticated requests.
So even HTML scraping wouldn't work as you are redirected to `/login`.

**Comment by Kikobeats** [comment]
Now the Instagram implementation is using [Microlink](https://microlink.io) service for getting the Instagram markup (residential proxy + prerendering under the hood).

Unfortunately, since those actions represent a cost, you need to supply your Microlink Pro plan API key.

Details at  https://unavatar.io/#instagram

I know this is not an ideal solution, but these days there is no way to get an Instagram avatar at scale with no cost, so at least people interested in this can get it without the pain of handle the infrastructure stuff on your side.
